[tool.poetry]
name = "mlx-omni-server"
version = "0.1.0"
description = ""
authors = ["madroid <madroidmaq@gmail.com>"]
readme = "README.md"
packages = [{include = "mlx_omni_server", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.4"
python-multipart = "^0.0.17"
pydantic = "^2.9.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
