[tool.poetry]
name = "mlx-omni-server"
version = "0.1.0"
description = ""
authors = ["madroid <madroidmaq@gmail.com>"]
readme = "README.md"
packages = [{ include = "mlx_omni_server", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.4"
python-multipart = "^0.0.17"
pydantic = "^2.9.2"
f5-tts-mlx = "^0.1.7"
uvicorn = "^0.32.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
httpx = "^0.27.2"

[tool.poetry.scripts]
start = "mlx_omni_server.main:start"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
